# Generated by Django 3.0.2 on 2020-03-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
